[global]
excludes = [".git/**", ".jj/**", ".tmp/**", "target/**", "**/node_modules/**"]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]

[formatter.tombi]
command = "tombi"
options = ["format"]
includes = ["*.toml"]
