[package]
name = "shepherdr-app"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
name = "shepherdr_app_lib"

[dependencies]
rustc-hash = "2.1.3"
shepherdr-core = { path = "../shepherdr-core" }
tauri = { version = "2.11.5", features = ["tray-icon"] }
tauri-plugin-single-instance = "2.4.3"
tokio = {
  version = "1.53.1",
  default-features = false,
  features = ["macros", "process", "rt", "sync", "time"]
}

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[lints]
workspace = true
