name: commitlint
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  commitlint:
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@bd75e283c44936a1876b5194ffb88a54f847deee # main
    permissions:
      contents: read
      actions: read
