name: GitHub Actions Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: cffnpwr/actions/.github/workflows/github-actions-lint.yaml@bd75e283c44936a1876b5194ffb88a54f847deee # main
    permissions:
      contents: read
